"""Turning a parsed report into findings, trends, and a retrieval query.

No interpretation here is generated by a model. Abnormality comes from the
reference interval, criticality from the table, and direction of travel from
arithmetic on two reports. The model's job downstream is to *explain* these
findings from retrieved sources, not to decide them.
"""

from __future__ import annotations

from dataclasses import dataclass

from medassist.core.enums import Severity
from medassist.core.models import LabAnalyte, LabReport
from medassist.reports.analytes import is_critical, lookup


@dataclass(frozen=True)
class Finding:
    analyte: str
    value: float
    unit: str
    flag: str
    severity: Severity
    interval: str
    critical: bool = False

    def describe(self) -> str:
        mark = " CRITICAL" if self.critical else ""
        return f"{self.analyte} {self.value:g} {self.unit} ({self.flag}, ref {self.interval}){mark}"


@dataclass(frozen=True)
class Trend:
    analyte: str
    previous: float
    current: float
    unit: str

    @property
    def delta(self) -> float:
        return self.current - self.previous

    @property
    def percent(self) -> float:
        if self.previous == 0:
            return 0.0
        return self.delta / abs(self.previous) * 100

    @property
    def direction(self) -> str:
        if abs(self.percent) < 5:
            return "stable"
        return "rising" if self.delta > 0 else "falling"

    def describe(self) -> str:
        return (
            f"{self.analyte} {self.previous:g} -> {self.current:g} {self.unit} "
            f"({self.direction}, {self.percent:+.0f}%)"
        )


def _severity(analyte: LabAnalyte) -> Severity:
    if is_critical(analyte):
        return Severity.CRITICAL
    if not analyte.abnormal:
        return Severity.INFO
    interval = lookup(analyte.name)
    if interval is None:
        return Severity.LOW
    # How far outside the interval, relative to its own width. A value 3x the
    # interval width beyond the bound is a different thing from one just over.
    span = None
    if interval.low is not None and interval.high is not None:
        span = interval.high - interval.low
    if not span:
        return Severity.MEDIUM
    if analyte.flag == "high" and interval.high is not None:
        excess = (analyte.value - interval.high) / span
    elif analyte.flag == "low" and interval.low is not None:
        excess = (interval.low - analyte.value) / span
    else:
        return Severity.MEDIUM
    return Severity.HIGH if excess > 0.5 else Severity.MEDIUM


def findings(report: LabReport) -> list[Finding]:
    out: list[Finding] = []
    for analyte in report.analytes:
        if not analyte.abnormal:
            continue
        low = "" if analyte.ref_low is None else f"{analyte.ref_low:g}"
        high = "" if analyte.ref_high is None else f"{analyte.ref_high:g}"
        out.append(
            Finding(
                analyte=analyte.name, value=analyte.value, unit=analyte.unit,
                flag=analyte.flag, severity=_severity(analyte),
                interval=f"{low}-{high}", critical=is_critical(analyte),
            )
        )
    rank = {Severity.CRITICAL: 0, Severity.HIGH: 1, Severity.MEDIUM: 2, Severity.LOW: 3, Severity.INFO: 4}
    return sorted(out, key=lambda f: rank[f.severity])


def trends(previous: LabReport, current: LabReport) -> list[Trend]:
    """Direction of travel for analytes present in both reports.

    A single abnormal value and a value that has doubled since March are
    different clinical facts, and only the second is visible longitudinally.
    """
    before = {a.name: a for a in previous.analytes}
    out: list[Trend] = []
    for analyte in current.analytes:
        earlier = before.get(analyte.name)
        if earlier is None:
            continue
        out.append(
            Trend(analyte=analyte.name, previous=earlier.value,
                  current=analyte.value, unit=analyte.unit or earlier.unit)
        )
    return sorted(out, key=lambda t: -abs(t.percent))


def requires_escalation(report: LabReport) -> bool:
    """Any critical-range value escalates, per the capability contract (§04.2)."""
    return any(is_critical(a) for a in report.analytes)


def retrieval_query(report: LabReport, limit: int = 4) -> str:
    """A query built from what is actually abnormal.

    Retrieving on the whole report drowns the abnormal values in the normal
    ones; the interesting content is the handful that are out of range.
    """
    names = [f.analyte for f in findings(report)][:limit]
    if not names:
        return "normal laboratory results interpretation"
    return " ".join(names) + " abnormal laboratory result meaning"
